# setting variables for CACHE
cache:

  # setting cache for VIEW
  view: "storage/cache/views" # <-- NOTE! It's either false for OFF or the path ("storage/cache/views") to where the cached views are stored...

  # setting cache for UPLOADS
  uploads:
    image:
      path: "storage/cache/image"